export const ADD_REMINDER = 'ADD_REMINDER';
export const EDIT_REMINDER = 'EDIT_REMINDER';
export const REMOVE_REMINDER = 'REMOVE_REMINDER';
export const ADD_LIST = 'ADD_LIST';
export const SET_TODO_LIST = 'SET_TODO_LIST';
export const TOGGLE_COMPLETE_REMINDER = 'TOGGLE_COMPLETE_REMINDER';
